site_name: Anthony's Corner
site_description: A blog about technology, DevOps, and personal insights.
site_url: https://trunghq-02.github.io/mkdocs-blog/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode 

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Technical
        - Personal
        - News
      pagination_per_page: 5
      post_slugify: !!python/object/apply:ext.slugs.slugify
        kwds:
          short: true
  - meta
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/github
      name: Anthony's GitHub
      link: https://github.com/TrungHQ-02
    - icon: fontawesome/brands/linkedin
      name: Anthony's LinkedIn
      link: https://www.linkedin.com/in/qu%E1%BB%91c-trung-ho%C3%A0ng-b363982b6/
  alternate:
    - name: English
      link: /
      lang: en
    - name: Vietnamese
      link: /
      lang: vi
  generator: false

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Blog:
     - blog/tags.md
     - blog/index.md
  - About: about.md
copyright: Copyright &copy; 2024 Anthony Hoang